import { ThemeProvider } from "@/context/ThemeContext";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { TodosProvider } from "@/context/TodosContext";
import { cookies } from "next/headers";
import { ThemeType } from "@/types/types";
import { Config } from "@/config";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const cookieStore = cookies();
  let theme = "light";
  if(cookieStore.has(Config.themeCookieKey)) {
    theme = cookieStore.get(Config.themeCookieKey)!.value;
  } 

  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider initialValue={theme as ThemeType}>
          <TodosProvider>
            {children}
          </TodosProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
